version: '3'

networks:
  web-network:

services:
  docker-nginx:
    build: 
      context: ./nginx
    ports:
      - "8080:80"
    tty: true
    volumes:
      - appcode:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - docker-php-fpm
    networks:
      - web-network

  docker-php-fpm:
    build: 
      context: ./php-fpm
    tty: true
    volumes:
      - appcode:/var/www
      - ./.env:/var/www/.env:ro
      - ./php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    networks:
      - web-network

  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data:/var/lib/mysql:delegated
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    networks:
      - web-network

  sspak:
    build: 
      context: ./snapshots
    depends_on:
      - db
    networks:
      - web-network
    volumes:
      - "./snapshots:/app/snapshots:rw"
      - ./.env:/app/www/.env:ro
      - "appcode:/app/www:ro"

volumes:
  db-data:
  appcode:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/Users/ahumphreys/Sites/dockerism/app/"  # location on nfs server of file/dir you want to mount